---
local_mounts:
  - mount_point: "{{ slurm_local_scratch_dir }}"
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: root
    mounted_mode: '0755'
    mount_options: rw,relatime,nofail,x-systemd.device-timeout=10
    type: ext4
...
