---
local_mounts:
  - mount_point: "{{ hpc_env_prefix }}"
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: "{{ envsync_group }}"
    mounted_mode: '2775'
    mount_options: rw,relatime,nofail,x-systemd.device-timeout=10
    type: ext4
...
