---
os_distribution: 'rocky9'
# This is enforcing that docs server uses `yum_repos` to create
# yum repositories, since docs servers do not use Pulp.
repo_manager: 'none'
#
# Firewall configuration.
#
iptables_allow_icmp_inbound:
  - "{{ all.ip_addresses['umcg']['net1'] }}"
  - "{{ all.ip_addresses['umcg']['net2'] }}"
  - "{{ all.ip_addresses['umcg']['net3'] }}"
  - "{{ all.ip_addresses['umcg']['net4'] }}"
  - "{{ all.ip_addresses['rug']['bwp_net'] }}"
  - "{{ all.ip_addresses['rug']['operator'] }}"
  - "{{ all.ip_addresses['gcc']['cloud_net'] }}"
  - "{{ fender_cluster.ip_addresses['corridor']['public'] }}"
  - "{{ gearshift_cluster.ip_addresses['airlock']['vlan16'] }}"
  - "{{ hyperchicken_cluster.ip_addresses['portal']['public'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ wingedhelix_cluster.ip_addresses['wh-porch']['vlan16'] }}"
  - "{{ betabarrel_cluster.ip_addresses['bb-porch']['vlan16'] }}"
  - "{{ copperfist_cluster.ip_addresses['cf-porch']['external'] }}"
iptables_allow_ssh_inbound:
  - "{{ fender_cluster.ip_addresses['corridor']['public'] }}"
  - "{{ gearshift_cluster.ip_addresses['airlock']['vlan16'] }}"
  - "{{ hyperchicken_cluster.ip_addresses['portal']['public'] }}"
  - "{{ nibbler_cluster.ip_addresses['tunnel']['vlan16'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
  - "{{ vaxtron_cluster.ip_addresses['foyer']['external'] }}"
  - "{{ wingedhelix_cluster.ip_addresses['wh-porch']['vlan16'] }}"
  - "{{ betabarrel_cluster.ip_addresses['bb-porch']['vlan16'] }}"
  - "{{ copperfist_cluster.ip_addresses['cf-porch']['external'] }}"
iptables_allow_http_inbound:
  - ANY
iptables_allow_https_inbound:
  - ANY
...
