---
#
# Firewall configuration.
#
iptables_allow_icmp_inbound:
  - ANY
iptables_allow_ssh_inbound:
  - ANY
iptables_allow_ssh_outbound:
  - ANY
iptables_allow_https_inbound:
  - ANY  # For DAVRODS.
iptables_allow_irods:
  - ANY
iptables_allow_postgresql_outbound:
  - ANY

ir_server_type: 'icat'                     # iRODS Server Type
ir_yum_packages: '{{ ir_yum_packages_4_3_0 }}' # Picked version of packages (defined in role defaults)
ir_client_server_policy: 'CS_NEG_REQUIRE'  # communicating using SSL (CS_NEG_REQUIRE) or without (CS_NEG_REFUSE
ir_ssl_certificate_chain_file: 'nemi_irods/localhost_and_chain_umcg-icat01.crt' # iRODS server certificate
ir_ssl_certificate_key_file: 'nemi_irods/localhost-umcg01.key' # iRODS server certificate's key
ir_ssl_dh_params_file: 'dhparams.pem'      # DHparam filename 

ir_service_account: 'irods'                # iRODS linux account under which iRODS runs
ir_service_account_home: '/home/{{ ir_service_account }}' # iRODS service account user's home folder
ir_admin_name: 'rods'                      # iRODS (and zone) account
ir_admin_pwd: '{{ icatV_admin_pwd }}'      # iRODS Vaulte main administrator password
ir_admin_home_path: '/{{ ir_zone }}/home/{{ ir_admin_name }}' # iRODS admin's home path
ir_salt: '{{ icatV_salt }}'                # iRODS Vaulted salt
ir_zone: 'nlumcg'                          # iRODS default main iRODS zone name
ir_zone_key: '{{ icatV_zone_key }}'        # iRODS Vaulted zone key 
ir_negotiation_key: '{{ icatV_negotiation_key }}' # iRODS Vaulted negotiation key
ir_ctrl_plane_key: '{{ icatV_ctrl_plane_key }}' # iRODS Vaulted control plane key
ir_local_res: 'rootResc'                   # iRODS local iRODS resource
ir_vault_path: '/var/lib/irods/Vault'      # iRODS default path to store files for local resource
ir_default_res: 'surfObjStore'             # iRODS default resource iRODS uploads to

davrods_install: true                      # to install davrods docker
davrods_docker_folder: 'davrods_docker'    # davrods docker folder name, relative to the user home directory
davrods_default_resource: '{{ ir_default_res }}' # default resource to upload files via davrods

tiering_install: False                     # True / False
ir_local_stage_res: 'demoRescStaging'      # Staging resource, before data moved to permanent resource
ir_local_stage_res_fol: '/tmp/irods/{{ ir_local_stage_res }}' # optional, only if it is local resource
ir_local_perm_res: 'demoRescPerm'          # Permanent resource, where it will keep data indefinitely
ir_local_perm_res_fol: '/tmp/irods/{{ ir_local_perm_res }}' # optional, only if it is local resource

pgsql_server: "local"                      # "local" or "remote" PostgreSQL server
remote_psql_server_ca: "nemi_irods/remote_psql_server_ca.crt"   # (optional) remote servers's CA certificate
...
