---
stack_prefix: 'build'
stack_name: "{{ stack_prefix }}_library"  # stack_name must match the name of the folder that contains this vars.yml file.
availability_zone: nova
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    router:
      next-hop-address: '10.10.1.1'
      external_network: vlan16
    create: true
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
functional_admin_group: 'funad'
regular_groups:
  - name: "{{ functional_admin_group }}"
  - name: 'vipt'
regular_users:
  - name: 'dhendriksen'
    groups: ['vipt']
  - name: 'bcharbon'
    groups: ['vipt']
  - name: 'svandenhoek'
    groups: ['vipt']
  - name: 'mbijlsma'
    groups: ['vipt']
  - name: 'jkloosterman'
    groups: ['vipt']
  - name: 'mbeukers'
    groups: ['vipt']
  - name: 'gvdvries'
    groups: ['vipt']
  - name: 'rkanninga'
    groups: ['vipt']
  - name: 'kdelange'
    groups: ['vipt']
sudoers:
  - who: ['%vipt']
    become: 'ALL'
    name: 'apptainer'
    command: '/bin/apptainer'
use_ldap: false
create_ldap: false
use_sssd: false
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network:  external_unfiltered
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: vaxtron_cluster
    hosts:
      - hostname: foyer
        network: external
...
