---
- name: Install Samba.
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - samba
      - samba-common
      - samba-client
      - cifs-utils
  notify: restart_smb
  become: true

- name: Deploy /etc/samba/smb.conf.
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0755'
  notify: reload_smb
  become: true

- name: Check if base path for each samba share exists.
  ansible.builtin.stat:
    path: "{{ item['base'] }}"
  register: smb_server_shares_base_status
  loop: "{{ smb_server_shares | flatten(levels=1) }}"
  become: true

- name: Fail if base path for a samba share is missing.
  ansible.builtin.fail:
    msg:
      - "The base path {{ item['base'] }} is missing for samba share {{ item['name'] }}."
      - "Another role should have been deployed first or your config is incomplete."
  vars:
    query: "[?stat.path=='{{ item.base }}'].stat.exists"
  when: smb_server_shares_base_status.results | json_query(query) | first is false
  loop: "{{ smb_server_shares | flatten(levels=1) }}"

- name: Create samba users.
  ansible.builtin.shell: |
    set -e
    set -u
    set -o pipefail
    pdbedit --user='{{ item.name }}' 2>&1 > /dev/null \
     || (echo '{{ smb_server_credentials[item.name] }}'; echo '{{ smb_server_credentials[item.name] }}') \
        | smbpasswd -s -a '{{ item.name }}'
  args:
    executable: /bin/bash
  register: smb_server_create_users
  changed_when: "'Added user' in smb_server_create_users.stdout"
  loop: "{{ smb_server_users }}"
  loop_control:
    label: "{{ item.name }}"
  become: true
  no_log: true

- name: Configure passwords for samba users.
  ansible.builtin.shell: |
    set -e
    set -u
    set -o pipefail
    smbclient -U '{{ item.name }}%{{ smb_server_credentials[item.name] }}' -L 127.0.0.1 2>&1 > /dev/null \
      || (echo '{{ smb_server_credentials[item.name] }}'; echo '{{ smb_server_credentials[item.name] }}') \
         | smbpasswd '{{ item.name }}'
  args:
    executable: /bin/bash
  register: smb_server_check_users
  changed_when: "'New SMB password' in smb_server_check_users.stdout"
  loop: "{{ smb_server_users }}"
  loop_control:
    label: "{{ item.name }}"
  become: true
  no_log: true

- name: Create samba share folders.
  ansible.builtin.file:
    path: "{{ item.0.base }}/{{ item.1.path }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
    state: directory
  loop_control:
    label: "Directory {{ item.0.base }}/{{ item.1.path }} owned by {{ item.1.owner }}:{{ item.1.group }} with mode {{ item.1.mode }}"
  loop: "{{ smb_server_shares | subelements('subtree') }}"
  become: true

- name: Enable services.
  ansible.builtin.systemd:
    name: smb
    state: started
    enabled: true
    daemon_reload: true
  become: true
...
