---
- name: Running > admin_users < role on first batch of machines
  hosts:
    - jumphost
    - data_transfer
    - logs
  roles:
    - admin_users
- name: Running > admin_users < role on second batch of machines
  hosts:
    - repo
    - cluster
    - docs
    - jenkins
    - build_server
  roles:
    - admin_users
...
