---
- name: Running > logs_client < role
  hosts:
    - jumphost
    - cluster
    - repo
    - logs
  roles:
    - role: logs_client
      when: (syslog_external_servers is defined and ( syslog_external_servers|length>0 )) or
        ( logs_class is defined )
...
