#
# Example to use NFS based home dirs exported from the UI and mounted on the compute nodes.
#
---
- name: Export /home on NFS server.
  hosts: user_interface
  roles:
     - nfs_home_server

- name: Mount /home on NFS clients.
  hosts: compute_node
  roles:
     - nfs_home_client
...