---
- hosts: repo
  #
  # Use hard coded strategy linear to disable mitogen when present as it
  # cannot handle this combiantion of
  #     vars:
  #       ansible_python_interpreter: "/admin/{{ repo_management_user }}/pulp-cli.venv/bin/python3"
  #     become: true
  #     become_user: "{{ repo_management_user }}"
  # to execute a task using a different user and inside a Python virtual environment
  # located in the home dir of that different user: bummer.
  #
  strategy: linear
  roles:
    - role: pulp_server
...
