---
- name: Install sssd role.
  hosts:
    - jumphost
    - cluster
    - data_transfer
  roles:
    - sssd
    - sshd  # Always re-run sshd role after potentially changing the logic to fetch public keys.
...
