---
- name: Running > yum_repos < role
  hosts:
   - jumphost
   - cluster
   - build_server
   - data_transfer
   - docs
   - logs
   - repo
  roles:
   - role: yum_repos
     when: repo_manager == 'none'
...
