---
# Configuring according to the https://www.postgresql.org/docs/current/libpq-ssl.html
- name: Ensure that .postgresql directory exists in home and is owned by irods service user
  ansible.builtin.file:
    path: '{{ ir_service_account_home }}/.postgresql'
    state: directory
    owner: '{{ ir_service_account }}'
    group: '{{ ir_service_account }}'
    mode: '0700'
  become_user: '{{ ir_service_account }}'
  become: true

- name: Create empty remote server's CA revocation list file inside .postgresql folder
  ansible.builtin.copy:
    content: ''
    dest: '{{ ir_service_account_home }}/.postgresql/root.crl'
    force: false
    owner: '{{ ir_service_account }}'
    group: '{{ ir_service_account }}'
    mode: '0644'
  become_user: '{{ ir_service_account }}'
  become: true

- name: Deploy remote server's CA signing certificate as root.crt into .postgresql folder
  ansible.builtin.copy:
    src: 'files/{{ stack_name }}/{{ remote_psql_server_ca }}'
    dest: "{{ ir_service_account_home }}/.postgresql/root.crt"
    owner: "{{ ir_service_account }}"
    group: "{{ ir_service_account }}"
    mode: '0644'
  become_user: '{{ ir_service_account }}'
  become: true

- name: Deploy remote server's CA signing certificate into /etc/irods folder
  ansible.builtin.copy:
    src: 'files/{{ stack_name }}/{{ remote_psql_server_ca }}'
    dest: '/etc/irods/{{ remote_psql_server_ca | basename }}'
    owner: '{{ ir_service_account }}'
    group: '{{ ir_service_account }}'
    mode: '0644'
  become_user: '{{ ir_service_account }}'
  become: true
  when: remote_psql_server_ca is defined

- name: Deploy certificate and key to be used for psql client calls
  ansible.builtin.copy:
    src: 'files/{{ stack_name }}/{{ item.name }}'
    dest: '{{ ir_service_account_home }}/.postgresql/{{ item.dest }}'
    owner: '{{ ir_service_account }}'
    group: '{{ ir_service_account }}'
    mode: '{{ item.mode }}'
    decrypt: true
    force: true
  with_items:
    - name: '{{ ir_ssl_certificate_key_file }}'
      dest: 'postgresql.key'
      mode: '0600'
    - name: '{{ ir_ssl_certificate_chain_file }}'
      dest: 'postgresql.crt'
      mode: '0644'
  become: true
  notify: irodsctl_restart

- name: Install additional packages in order to work with remote database (>=4.3.0)
  ansible.builtin.package:
    name:
      - unixODBC-devel
      - python3-devel
      - gcc-c++
    state: latest
  become: true
  notify: irodsctl_restart

- name: Install pyodbc with pip3
  ansible.builtin.pip:
    name: pyodbc
    state: latest
    executable: pip3
  become: true
  become_user: '{{ ir_service_account }}'

...
