---
- name: Install fuse-sshfs
  ansible.builtin.package:
    name: fuse-sshfs
    state: present
  become: true

- name: "Create a {{ archive_ssh_key_type }} SSH key for root user"
  ansible.builtin.user:
    name: "root"
    generate_ssh_key: true
    ssh_key_file: "{{ archive_ssh_key_location }}"
    ssh_key_type: "{{ archive_ssh_key_type }}"
  register: make_root_keypair
  become: true

- name: Keys generated and we stop the role
  ansible.builtin.debug:
    msg:
      - "SSH key pair was created for the root user on {{ inventory_hostname }}."
      - "Now you must now copy {{ inventory_hostname }}:{{ archive_ssh_key_location }}.pub to {{ item['archive_system'] }}:/home/{{ item['archive_user'] }}/.ssh/authorized_keys."
  loop: "{{ remote_archive }}"
  loop_control:
    label: "{{ item['name'] }}"
  when: make_root_keypair.changed is true # noqa no-handler
  failed_when: true

- name: Create .ssh folder structure
  ansible.builtin.file:
    path: "/root/.ssh/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0700"
    state: directory
  with_items:
    - "conf.d"
    - "tmp"
  become: true

- name: Set list of unique ssh hosts
  ansible.builtin.set_fact:
    archive_unique_hosts: "{{ remote_archive | map(attribute='archive_system', default='') | unique }}"

- name: Deploy ssh configuration settings for accessing archive
  ansible.builtin.template:
    src: templates/ssh_configuration
    dest: /root/.ssh/conf.d/remote_archive
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Collect all ssh fingerprints
  ansible.builtin.set_fact:
    archive_all_fingerprints: "{{ archive_all_fingerprints | default([]) + [item.0.archive_system + ' ' + item.1] }}"
  with_subelements:
    - "{{ remote_archive | default([], true) | list }}"
    - 'archive_system_fingerprints'

- name: Write public keys into known_hosts
  ansible.builtin.lineinfile:
    path: /root/.ssh/known_hosts
    state: present
    search_string: "{{ item }}"
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: "0600"
  when: archive_all_fingerprints is defined and archive_all_fingerprints | length > 0
  with_items: "{{ archive_all_fingerprints | unique }}"
  become: true

- name: Configure ssh to check for extra configration files in conf.d
  ansible.builtin.lineinfile:
    path: /root/.ssh/config
    line: "Include conf.d/*"
    create: true
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Check connection and ensure that group folder on remote archive system exists
  ansible.builtin.command: >
    ssh -i {{ archive_ssh_key_location }} {{ item.0.archive_user }}@{{ item.0.archive_system }}
    "mkdir -p {{ item.0.archive_remote_top_dir }}/{{ item.0.local_top_level_mount }}/{{ item.1 }}/{{ item.0.name }}"
  register: archive_dir_test
  changed_when: false
  with_subelements:
    - "{{ remote_archive | default([], true) | list }}"
    - 'groups'
  become: true
...
