---
- name: 'Restart iptables based firewall deamons (IPv4 and IPv6).'
  ansible.builtin.service:
    name: "{{ item }}"
    state: 'restarted'
    daemon_reload: 'yes'
  with_items:
    - 'iptables'
    - 'ip6tables'
  become: true
  listen: restart_iptables

- name: 'Configure iptables based firewalls (IPv4 and IPv6).'
  ansible.builtin.command:
    cmd: '/etc/sysconfig/iptables-init.bash'
  changed_when: true
  become: true
  listen: configure_iptables
...
