site_name: "{{ slurm_cluster_name | capitalize }} HPC cluster"
site_url: "http://{{ first_doc_server_address }}/{{ slurm_cluster_name }}/"
use_directory_urls: true
theme:
  name: readthedocs
  highlightjs: false
  hljs_languages:
    - yaml
  collapse_navigation: false
  titles_only: false
site_dir: "/var/www/html/{{ slurm_cluster_name }}/"
extra_css:
    - css/custom.css
nav:
  - Home: 'index.md'
  - About: 
    - 'Cluster': 'cluster.md'
    - 'License': 'license.md'
    - 'Contact': 'contact.md'
  - Requesting Accounts:
    - 'Accounts, security and privacy': 'accounts.md'
    - 'Generate SSH key pair for Windows': 'generate-key-pair-mobaxterm.md'
    - 'Generate SSH key pair for macOS & Linux': 'generate-key-pair-openssh.md'
  - Logins:
    - 'Jumphosts, UIs and sessions': 'logins.md'
    - 'SSH config & login for Windows clients': 'logins-windows.md'
    - 'SSH config for macOS clients': 'logins-macos-config.md'
    - 'SSH config for Linux clients': 'logins-linux-config.md'
    - 'SSH login for macOS & Linux clients': 'logins-macos-linux.md'
    - 'Customize your environment': 'custom-environment.md'
  - Storage:
    - 'Keep - What is stored where on {{ slurm_cluster_name | capitalize }}': 'storage.md'
    - 'Data transfers - How to move data to / from {{ slurm_cluster_name | capitalize }}': 'datatransfers.md'
{% if groups['data_transfer'] is defined and groups['data_transfer'] | length >= 1 %}
    - 'Data transfers - Using a dedicated data transfer server': 'dedicated-dt-server-overview.md'
{% endif %}
  - Compute:
    - 'Crunch - How to manage jobs on {{ slurm_cluster_name | capitalize }}': 'analysis.md'
{% if groups['compute_node'] | map('extract', hostvars, 'gpu_count') | select('defined') | default([0], true) | map('int') | sum > 0 %}
    - 'GPU jobs - submitting and managing': 'gpu.md'
{% endif %}
  - Technical Specifications:
    - 'Details on the {{ slurm_cluster_name | capitalize }} HPC environment': 'specifications.md'
  - Software:
    - 'Using and installing software': 'software.md'
    - 'R packages': 'R.md'
    - 'RStudio': 'RStudio.md'
    - 'Jupyter notebooks': 'Jupyter.md'
    - 'Apptainer (Singularity)': 'apptainer.md'
    - 'Nextflow': 'nextflow.md'
    - 'Python (Virtual Environment)': 'python.md'
{% if 'hyperchicken' in slurm_cluster_name or 'fender' in slurm_cluster_name %}
  - Group Specific Documentation:
    - 'Solve-RD - How to find and work with Solve-RD data': 'solve-rd.md'
{% endif %}
#    - 'Support - FAQs, mailinglists & courses': 'support.md'
