---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
  listen: "nginx_reload"

- name: New key fail at the end of the role
  ansible.builtin.fail:
    msg: >-
      "Newly generated {{ repo_user }} public key must be added to the users.yml"
      "Then rerun single_role_playbooks/regular_users.yml role on the SECONDARY servers!"
  listen: rm_new_public_key
...
