---
- name: "Enable crb repo (dependency for EPEL 9.x)"
  ansible.builtin.shell:
    cmd: dnf repolist crb && dnf config-manager --set-enabled crb
  register: epel_dnf_result_crb
  changed_when: "'disabled' in epel_dnf_result_crb.stdout"
  become: true

- name: Install EPEL repo.
  ansible.builtin.package:
    state: latest
    update_cache: true
    name: epel-release
  become: true

#
# EPEL does not have URLs for major.minor versions.
#
- name: 'Patch broken metalink in /etc/yum.repos.d/epel.repo file and replace $releasever with major version number only.'
  ansible.builtin.replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: '\$releasever'
    replace: '9'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  become: true

- name: Check the status of EPEL repo.
  ansible.builtin.shell:
    cmd: dnf repolist epel
  register: epel_dnf_result_epel_before
  changed_when: false
  become: true

- name: Enable EPEL repo.
  ansible.builtin.shell:
    cmd: dnf config-manager --set-enabled epel && dnf repolist epel
  register: epel_dnf_result_epel
  changed_when:
    - "'disabled' in epel_dnf_result_epel_before.stdout"
    - "'enabled' in epel_dnf_result_epel.stdout"
  when:
   - "'disabled' in epel_dnf_result_epel_before.stdout"
  become: true
...
