---
slurm_cluster_name: 'fender'
stack_domain: ''
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'fd'
slurm_version: '22.05.2-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01-12]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
logs_class: 'research'
repo_manager: 'pulp'
os_distribution: 'centos7'
figlet_font: 'slant'
motd: "To solve or not to solve, that's the question."
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs-on-bateleur
        network: external
  - group: donbot_azure
    nodes:
      - name: ladap
        network: donbot_external_network
use_ldap: true
use_sssd: true
ldap_domains:
  stack:
    uri: "ldaps://{{ stack_prefix }}-dai"
    base: "dc={{ stack_name }},dc=local"
    schema: rfc2307bis
    min_id: 1000
    max_id: 21999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: memberOf
    group_member: member
    create_ldap: true
    ldap_db_index: 3  # Indices up to 2 are already used by default for the "config", "monitor" and "example" databases.
cloud_image: CentOS7-Cloud
cloud_user: centos
availability_zone: nova
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    gateway: '10.10.1.1'
    router_network: public
    type: management
    external: false
  - name: subnet-nfs-data-2541
    cidr: '10.35.141.0/24'
    allow_ingress:
      - 10.35.141.251/32  # NFS server
      - 10.35.141.252/32  # NFS server
      - 10.35.141.253/32  # NFS server
    type: storage
    external: true
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'dick'
  - 'gerben'
  - 'marieke'
  - 'marloes'
  - 'pieter'
  - 'roan'
  - 'sandi'
envsync_user: 'envsync'
envsync_group: 'depad'
functional_admin_group: 'funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'users'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
  - user: 'solve-rd-ateambot'
    groups: ['solve-rd']
  - user: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ljohansson'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ddanis'
    groups: ['users', 'solve-rd']
  - user: 'dhendriksen'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'wsteyaert'
    groups: ['users', 'solve-rd']
  - user: 'slaurie'
    groups: ['users', 'solve-rd']
  - user: 'jvdvelde'
    groups: ['users', 'solve-rd']
  - user: 'fmusacchia'
    groups: ['users', 'solve-rd']
  - user: 'psivakumar'
    groups: ['users', 'solve-rd']
  - user: 'fandrade'
    groups: ['users', 'solve-rd']
  - user: 'gdemidov'
    groups: ['users', 'solve-rd']
  - user: 'amohan'
    groups: ['users']
  - user: 'dspalding'
    groups: ['users']
  - user: 'cthomas'
    groups: ['users', 'solve-rd']
  - user: 'mbenjamins'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'lmatalonga'
    groups: ['users', 'solve-rd']
  - user: 'gbullich'
    groups: ['users', 'solve-rd']
  - user: 'ebenetti'
    groups: ['users', 'solve-rd']
  - user: 'kdelange'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'sli'
    groups: ['users', 'solve-rd']
  - user: 'rschuele'
    groups: ['users', 'solve-rd']
  - user: 'jvandrovcova'
    groups: ['users', 'solve-rd']
  - user: 'itepaske'
    groups: ['users', 'solve-rd']
  - user: 'jpelaez'
    groups: ['users', 'solve-rd']
  - user: 'asommer'
    groups: ['users', 'solve-rd']
  - user: 'droelofs'
    groups: ['users', 'solve-rd']
  - user: 'dlagorce'
    groups: ['users', 'solve-rd']
  - user: 'gwarren'
    groups: ['users', 'solve-rd']
  - user: 'mmehtarizadeh'
    groups: ['users', 'solve-rd']
  - user: 'cveal'
    groups: ['users', 'solve-rd']
  - user: 'rthompson'
    groups: ['users', 'solve-rd']
  - user: 'alaner'
    groups: ['users', 'solve-rd']
  - user: 'edeboer01'
    groups: ['users', 'solve-rd']
  - user: 'adenommepichon'
    groups: ['users', 'solve-rd']
  - user: 'avitobello'
    groups: ['users', 'solve-rd']
  - user: 'yduffourd'
    groups: ['users', 'solve-rd']
  - user: 'elopez02'
    groups: ['users', 'solve-rd']
  - user: 'amarcegrau'
    groups: ['users', 'solve-rd']
  - user: 'cwilke'
    groups: ['users', 'solve-rd']
  - user: 'ajackson'
    groups: ['users', 'solve-rd']
  - user: 'byaldiz'
    groups: ['users', 'solve-rd']
  - user: 'bcharbon'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'amaver'
    groups: ['users', 'solve-rd']
  - user: 'cgilissen'
    groups: ['users', 'solve-rd']
  - user: 'arump'
    groups: ['users', 'solve-rd']
  - user: 'abuhrmann'
    groups: ['users', 'solve-rd']
  - user: 'mferreira'
    groups: ['users', 'solve-rd']
  - user: 'iparamonov'
    groups: ['users', 'solve-rd']
  - user: 'ohongnat'
    groups: ['users', 'solve-rd']
  - user: 'mslofstra'
    groups: ['users', 'solve-rd']
  - user: 'dwilliam'
    groups: ['users', 'solve-rd']
  - user: 'mbeukers'
    groups: ['users', 'solve-rd']
  - user: 'fgao'
    groups: ['users', 'solve-rd']
  - user: 'druvolo'
    groups: ['users', 'solve-rd']
  - user: 'ftranmauthem'
    groups: ['users', 'solve-rd']
  - user: 'mjohari'
    groups: ['users', 'solve-rd']
  - user: 'mchahdil'
    groups: ['users', 'solve-rd']
  - user: 'aesteve'
    groups: ['users', 'solve-rd']
  - user: 'cdoornbos'
    groups: ['users', 'solve-rd']
  - user: 'kmaassen'
    groups: ['users', 'solve-rd']
  - user: 'gbeen'
    groups: ['users', 'solve-rd']
  - user: 'dmei'
    groups: ['users', 'solve-rd']
  - user: 'hmorsy'
    groups: ['users', 'solve-rd']
  - user: 'kzguro'
    groups: ['users', 'solve-rd']
  - user: 'jklimp'
    groups: ['users', 'solve-rd']
  - user: 'asalazarvillacorta'
    groups: ['users', 'solve-rd']
  - user: 'vyepez'
    groups: ['users', 'solve-rd']
  - user: 'fbrechtmann'
    groups: ['users', 'solve-rd']
  - user: 'cmertes'
    groups: ['users', 'solve-rd']
  - user: 'umcg-molgenis'
    groups: ['users']
  - user: 'svandenhoek'
    groups: ['users', 'solve-rd']
  - user: 'pacthoen'
    groups: ['users', 'solve-rd']
  - user: 'jgagneur'
    groups: ['users', 'solve-rd']
  - user: 'slondhe'
    groups: ['users', 'solve-rd']
  - user: 'dbeijer'
    groups: ['users', 'solve-rd']
  - user: 'jmueller'
    groups: ['users', 'solve-rd']
  - user: 'nsmal'
    groups: ['users', 'solve-rd']
  - user: 'bestevez'
    groups: ['users', 'solve-rd']
  - user: 'msynofzik'
    groups: ['users', 'solve-rd']
  - user: 'wmacken'
    groups: ['users', 'solve-rd']
  - user: 'klohmann'
    groups: ['users', 'solve-rd']
  - user: 'sadiaw'
    groups: ['users', 'solve-rd']
  - user: 'dndebento'
    groups: ['users', 'solve-rd']
  - user: 'hhengel'
    groups: ['users', 'solve-rd']
  - user: 'jschulzehentrich'
    groups: ['users', 'solve-rd']
  - user: 'atopf'
    groups: ['users', 'solve-rd']
  - user: 'ejung'
    groups: ['users', 'solve-rd']
  - user: 'jbaptist'
    groups: ['users', 'solve-rd']
  - user: 'mdabad'
    groups: ['users', 'solve-rd']
  - user: 'mbarrero'
    groups: ['users', 'solve-rd']
  - user: 'jkegele'
    groups: ['users', 'solve-rd']
  - user: 'mschlotterbek'
    groups: ['users', 'solve-rd']
  - user: 'jpark'
    groups: ['users', 'solve-rd']
  - user: 'izaharieva'
    groups: ['users', 'solve-rd']
  - user: 'kpolavarapu'
    groups: ['users', 'solve-rd']
  - user: 'izaganas'
    groups: ['users', 'solve-rd']
  - user: 'mmaran'
    groups: ['users', 'solve-rd']
  - user: 'bmartinez'
    groups: ['users', 'solve-rd']
  - user: 'elopez'
    groups: ['users', 'solve-rd']
  - user: 'oakselkilicarslan'
    groups: ['users', 'solve-rd']
  - user: 'mterradas'
    groups: ['users', 'solve-rd']
  - user: 'mkarakaya'
    groups: ['users', 'solve-rd']
  - user: 'rjimenezheredia'
    groups: ['users', 'solve-rd']
  - user: 'gastuti'
    groups: ['users', 'solve-rd']
  - user: 'gbonne'
    groups: ['users', 'solve-rd']
  - user: 'kabbott'
    groups: ['users', 'solve-rd']
  - user: 'lryba'
    groups: ['users', 'solve-rd']
  - user: 'hghani'
    groups: ['users', 'solve-rd']
  - user: 'eraineri'
    groups: ['users', 'solve-rd']
sudoers:
  - who: ['%solve-rd']
    become: 'solve-rd-dm'
  - who: ['%umcg-atd']
    become: 'umcg-atd-dm'
  - who: ['%solve-rd']
    become: 'solve-rd-ateambot'
#
# Shared storage related variables
#
pfs_mounts:
  - pfs: ecst02
    source: '10.35.141.252:/solve-rd-98599485/'
    type: nfs4
    rw_options: 'defaults,_netdev,noatime,nodiratime,rw'
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
lfs_mounts:
  - lfs: home
    pfs: ecst02
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp10
    pfs: ecst02
    groups:
      - name: umcg-atd
      - name: solve-rd
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_node'] }}"
  - lfs: prm10
    pfs: ecst02
    groups:
      - name: umcg-atd
      - name: solve-rd
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: env10
    pfs: ecst02
    ro_machines: "{{ groups['compute_node'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
ega_fuse_client_mounts:
  solve_rd: '/groups/solve-rd/prm10/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
