---
slurm_cluster_name: 'forkhead'
stack_domain: ''  # Only add hpc.rug.nl domain when jumphost is registered in DNS.
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'fh'
slurm_version: '22.05.2-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: forkhead  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.25G"'
repo_manager: 'none'
os_distribution: 'centos7'
figlet_font: 'ogre'
motd: |
      =========================================================
          Welcome to {{ slurm_cluster_name | capitalize }}
      =========================================================
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs-on-bateleur
        network: external
use_ldap: true
create_ldap: false
use_sssd: true
ldap_domains:
  stack:
    uri: "ldaps://{{ slurm_cluster_name }}"
    base: "dc=rug,dc=nl" # in case of replication, the base and replication_provider_base must match!
    schema: rfc2307
    min_id: 50100000
    max_id: 55999999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: groupMembership
    group_member: memberUid
    group_object_class: groupofnames
    group_quota_soft_limit_template: ruggroupumcgquotaLFSsoft
    group_quota_hard_limit_template: ruggroupumcgquotaLFS
    create_ldap: true
    ldap_db_index: 3  # Indices up to 2 are already used by default for the "config", "monitor" and "example" databases.
    replication_provider_uri: ldap://172.19.34.180
    replication_provider_base: dc=rug,dc=nl

nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
stack_networks:
  - name: vnet-medgen-t
    cidr: '10.96.52.12/24'
    type: management
    external: true
iptables_allow_icmp_inbound:
  - "{{ all.ip_addresses['umcg']['internal1'] }}"
  - "{{ all.ip_addresses['umcg']['basiswerkplek'] }}"
  - "{{ all.ip_addresses['umcg']['win10vdi'] }}"
iptables_allow_ssh_inbound:
  - "{{ all.ip_addresses['umcg']['internal1'] }}"
  - "{{ all.ip_addresses['umcg']['basiswerkplek'] }}"
  - "{{ all.ip_addresses['umcg']['win10vdi'] }}"
iptables_allow_ssh_outbound:
  - "{{ wingedhelix_cluster.ip_addresses['wh-porch']['vlan16'] }}"
  - "{{ betabarrel_cluster.ip_addresses['bb-porch']['vlan16'] }}"
  - "{{ copperfist_cluster.ip_addresses['cf-porch']['external'] }}"
main_backup_folder: '/mnt/pssd_backup/'
local_backups: # list of folders for cron to make daily backup
  - name: apps # don't modify after once deployed!
    src_path: '/apps'
    frequency:
     - { name: 'daily', hour: '5', minute: '47', day: '*', weekday: '*', month: '*', keep: '60', disabled: 'false' }
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'ger'
  - 'gerben'
  - 'henkjan'
  - 'kim'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'robin'
  - 'sandi'
  - 'wim'
data_transfer_only_group: 'umcg-sftp-only'
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
functional_users_group: 'umcg-funus'  # For all functional accounts. Used in /etc/security/access.conf.
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - "{{ functional_users_group }}"
  - 'umcg-atd'
  - 'umcg-gap'
  - 'umcg-gd'
  - 'umcg-genomescan'
  - 'umcg-gsad'
  - 'umcg-gst'
  - 'umcg-lab'
  - 'umcg-labgnkbh'
  - 'umcg-patho'
  - 'umcg-vipt'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}", "{{ functional_users_group }}"]
  - user: 'umcg-atd-ateambot'
    groups: ['umcg-atd', 'umcg-gsad', "{{ functional_users_group }}"]
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd', "{{ functional_users_group }}"]
  - user: 'umcg-gap-ateambot'
    groups: ['umcg-gap', "{{ functional_users_group }}"]
  - user: 'umcg-gap-dm'
    groups: ['umcg-gap', "{{ functional_users_group }}"]
  - user: 'umcg-gd-ateambot'
    groups: ['umcg-gd', 'umcg-gap', "{{ functional_users_group }}"]
  - user: 'umcg-gd-dm'
    groups: ['umcg-gd', "{{ functional_users_group }}"]
  - user: 'umcg-genomescan-ateambot'
    groups: ['umcg-genomescan', "{{ functional_users_group }}"]
  - user: 'umcg-genomescan-dm'
    groups: ['umcg-genomescan', "{{ functional_users_group }}"]
  - user: 'umcg-gsad-ateambot'
    groups: ['umcg-gsad', "{{ functional_users_group }}"]
  - user: 'umcg-gsad-dm'
    groups: ['umcg-gsad', "{{ functional_users_group }}"]
  - user: 'umcg-gst-ateambot'
    groups: ['umcg-gst', "{{ functional_users_group }}"]
  - user: 'umcg-gst-dm'
    groups: ['umcg-gst', "{{ functional_users_group }}"]
  - user: 'umcg-labgnkbh-ateambot'
    groups: ['umcg-labgnkbh', "{{ functional_users_group }}"]
  - user: 'umcg-labgnkbh-dm'
    groups: ['umcg-labgnkbh', "{{ functional_users_group }}"]
  - user: 'umcg-patho-ateambot'
    groups: ['umcg-patho', "{{ functional_users_group }}"]
  - user: 'umcg-patho-dm'
    groups: ['umcg-patho', "{{ functional_users_group }}"]
  - user: 'umcg-vipt-dm'
    groups: ['umcg-vipt', "{{ functional_users_group }}"]
sudoers:
  - who: ['%umcg-atd']
    become: 'umcg-atd-ateambot'
  - who: ['%umcg-atd']
    become: 'umcg-atd-dm'
  - who: ['%umcg-gap']
    become: 'umcg-gap-ateambot'
  - who: ['%umcg-gap']
    become: 'umcg-gap-dm'
  - who: ['%umcg-gd']
    become: 'umcg-gd-ateambot'
  - who: ['%umcg-gd']
    become: 'umcg-gd-dm'
  - who: ['%umcg-genomescan']
    become: 'umcg-genomescan-ateambot'
  - who: ['%umcg-genomescan']
    become: 'umcg-genomescan-dm'
  - who: ['%umcg-gsad']
    become: 'umcg-gsad-ateambot'
  - who: ['%umcg-gsad']
    become: 'umcg-gsad-dm'
  - who: ['%umcg-gst']
    become: 'umcg-gst-ateambot'
  - who: ['%umcg-gst']
    become: 'umcg-gst-dm'
  - who: ['%umcg-labgnkbh']
    become: 'umcg-labgnkbh-ateambot'
  - who: ['%umcg-labgnkbh']
    become: 'umcg-labgnkbh-dm'
  - who: ['%umcg-patho']
    become: 'umcg-patho-ateambot'
  - who: ['%umcg-patho']
    become: 'umcg-patho-dm'
  - who: ['%umcg-vipt']
    become: 'umcg-vipt-dm'
#
# Shared storage related variables
#
pfs_mounts:
  - pfs: pssd # must already be in /etc/fstab and mounted - f.e. /dev/sda > /mnt/local_raid (pfs somename must be same as /mnt/somename)
    device: ''
    source: '/mnt'
    type: 'none'
    rw_options: 'bind,rw'
    ro_options: 'bind,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
  - pfs: 'medgen_zincfinger$'
    source: '//storage5.umcg.nl'
    type: cifs    # checked with cat /proc/filesystem
    rw_options: 'vers=3.0,mfsymlinks,rw,soft,perm,dir_mode=02750,file_mode=0640'
    ro_options: 'vers=3.0,mfsymlinks,ro,soft,perm,dir_mode=02750,file_mode=0640'
    machines: "{{ groups['chaperone'] }}"
  - pfs: 'medgen_leucinezipper$'
    source: '//storage5.umcg.nl'
    type: cifs    # checked with cat /proc/filesystem
    rw_options: 'vers=3.0,mfsymlinks,rw,soft,perm,dir_mode=02750,file_mode=0640'
    ro_options: 'vers=3.0,mfsymlinks,ro,soft,perm,dir_mode=02750,file_mode=0640'
    machines: "{{ groups['chaperone'] }}"
  - pfs: 'medgen_wingedhelix$'
    source: '//storage5.umcg.nl'
    type: cifs    # checked with cat /proc/filesystem
    rw_options: 'vers=3.0,mfsymlinks,rw,soft,perm,dir_mode=02750,file_mode=0640'
    ro_options: 'vers=3.0,mfsymlinks,ro,soft,perm,dir_mode=02750,file_mode=0640'
    machines: "{{ groups['chaperone'] }}"
lfs_mounts:
  - lfs: home
    pfs: pssd
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp12
    pfs: pssd
    groups:
      - name: umcg-atd
      - name: umcg-gap
      - name: umcg-gd
      - name: umcg-genomescan
      - name: umcg-gsad
      - name: umcg-gst
      - name: umcg-lab
        mode: '2750'
      - name: umcg-vipt
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_node'] }}"
  - lfs: prm05
    pfs: 'medgen_zincfinger$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      - name: umcg-gsad
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: dat05
    pfs: 'medgen_zincfinger$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      #- name: umcg-genomescan  Do not use production groups while still in development phase.
      - name: umcg-gsad
      - name: umcg-gst
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: prm06
    pfs: 'medgen_leucinezipper$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      - name: umcg-gsad
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: dat06
    pfs: 'medgen_leucinezipper$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      #- name: umcg-genomescan  Do not use production groups while still in development phase.
      - name: umcg-gsad
      - name: umcg-gst
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: prm07
    pfs: 'medgen_wingedhelix$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      - name: umcg-gsad
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: dat07
    pfs: 'medgen_wingedhelix$'
    groups:
      - name: umcg-atd
      #- name: umcg-gap         Do not use production groups while still in development phase.
      #- name: umcg-gd          Do not use production groups while still in development phase.
      #- name: umcg-genomescan  Do not use production groups while still in development phase.
      - name: umcg-gsad
      - name: umcg-gst
      #- name: umcg-vipt        Do not use production groups while still in development phase.
    rw_machines: "{{ groups['chaperone'] }}"
  - lfs: env12
    pfs: pssd
    ro_machines: "{{ groups['compute_node'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
smb_server_users:
  - name: sbsuser
    uid: 501
    groups:
      - name: umcg-lab
        gid: 55100194
  - name: illumina
    uid: 502
    groups:
      - name: umcg-gap
        gid: 55100225
smb_server_interfaces: 192.168.1.0/24  # in addition to 127.0.0.1, which must always be present.
smb_server_shares:
  - name: ngs
    comment: Share for sequencers
    path: /mnt/pssd/groups/umcg-lab/tmp12/sequencers
    users: sbsuser
    file_mode: 0640
    dir_mode: 0750
  - name: array
    comment: Share for array scanners
    path: /mnt/pssd/groups/umcg-gap/tmp12/rawdata/array/IDAT/
    users: illumina
    file_mode: 0660
    dir_mode: 0770
...
