---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Basic roles for all cluster machines part 2. <-==###'
  hosts:
    - cluster
  roles:
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - regular_users
    - lustre_client
    - nfs_client
    - shared_storage
    - role: soft_partition
      when: soft_partitions is defined
    - backup_local
...
