---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for data transfer servers. <-==###'
  hosts:
    - data_transfer
  roles:
    - interfaces
    - iptables
    - grub
    - role: yum_local
      when: local_yum_repository is defined
    - locale
    - logrotate
    - remove
    - update
    - logins
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - rsyncd
    - regular_users
    - role: local_storage
      when: local_mounts is defined and local_mounts | length > 0
    - cleanup_gs_data
    - nhc_standalone
    - modulejail  # Must come late/last after all required kernel modules are loaded.
...
