---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for documentation servers. <-==###'
  hosts:
    - docs
  roles:
    - iptables
    - grub
    - locale
    - logrotate
    - remove
    - update
    - sshd
    - basic_security
    - online_docs
...
