---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: 'Satisfy dependencies and install iCAT'
  hosts: irods
  roles:
    - iptables
    - ssh  # client
    - grub
    - locale
    - logrotate
    - logins
    - sshd
    - basic_security
    - remove
    - update
    - docker
    - irods
    - irods_davrods
...
