---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for jumphosts. <-==###'
  hosts:
    - jumphost
  roles:
    - iptables
    - grub
    - ssh  # client
    - role: yum_local
      when: local_yum_repository is defined
    - locale
    - logrotate
    - remove
    - update
    - logins
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - role: logs_client
      when: logs_class is defined
    - regular_users
    # Disabled monitoring: needs update. See also:
    # https://github.com/rug-cit-hpc/league-of-robots/issues/294
    # - node_exporter
    # - {role: grafana_proxy, when: ansible_hostname == 'airlock'}
...
