---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '##==-> Configure syslog servers. <-==###'
  roles:
    - iptables
    - grub
    - locale
    - regular_users
    - ssh  # client
    - update
    - role: yum_local
      when: local_yum_repository is defined
    - logrotate
    - sshd
    - basic_security
    - logs_server
  hosts: logs
...
