---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for standalone LDAP servers. <-==###'
  hosts:
    - ldap_server
  roles:
    - iptables
    - grub
    - ssh             # client
    - locale
    - logrotate
    - remove
    - update
    - logins
    - sshd
    - basic_security
    - ldap_server
    - regular_users   # to create lsaai user
    - cluster         # to install perun software
    - lsaai           # configure lsaai scripts and config files
...
