#
# This play depends on:
#   * cluster_part1.yml
#   * cluster_part2.yml
#
---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for SAIs. <-==###'
  hosts:
    - sys_admin_interface
  roles:
    - slurm
    - nhc_standalone
    # Disabled monitoring: needs update. See also:
    # https://github.com/rug-cit-hpc/league-of-robots/issues/294
    # - prom_server
    # - grafana
    # - cadvisor
...
