#
# This play depends on:
#   * cluster_part1.yml
#   * cluster_part2.yml
#
---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for UIs. <-==###'
  hosts:
    - user_interface
  roles:
    - cgroups
    - build_environment
    # Disabled monitoring: needs update. See also:
    # https://github.com/rug-cit-hpc/league-of-robots/issues/294
    # - slurm_exporter
    - slurm
    - sudoers
    - subgroup_directories
    - role: ega_fuse_client
      when: ega_fuse_client_mounts is defined and ega_fuse_client_mounts | length >= 1
...
