---
- name: Restart sshd
  ansible.builtin.service:
    name: "{{ basic_security_sshd_name }}"
    state: "{{ basic_security_ssh_restart_handler_state }}"
  become: true
  listen: basic_security_restart_sshd
...
