---
- name: 'Manage network interfaces on EL <= 7'
  ansible.builtin.import_tasks:
    file: el7.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] <= "7"

- name: 'Manage network connections and devices on EL >= 8'
  ansible.builtin.import_tasks:
    file: el8.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "8"
