---
- name: Install Slurm notification dependencies with yum.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name:
      - curl
  become: true

- name: Create folder for Slurm notification scripts.
  ansible.builtin.file:
    name: '/etc/slurm/notification_scripts'
    owner: root
    group: slurm
    mode: '0750'
    state: directory
  become: true

- name: Install notification scripts.
  ansible.builtin.template:
    src: "templates/notification_scripts/{{ item }}"
    dest: '/etc/slurm/notification_scripts/'
    owner: root
    group: slurm
    mode: '0750'
  loop:
    - nodes.bash
    - management.bash
  become: true

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Configure slurm triggers.
  ansible.builtin.command:
    cmd: |
         strigger --set --flags=perm {{ item }}
  register: slurm_strigger_result
  failed_when:
    - slurm_strigger_result.rc != 0
    - "'Duplicate' not in slurm_strigger_result.stderr"
  changed_when: slurm_strigger_result.rc == 0
  loop:
    - "-d -p '/etc/slurm/notification_scripts/nodes.bash'"
    - "-D -p '/etc/slurm/notification_scripts/nodes.bash'"
    - "-F -p '/etc/slurm/notification_scripts/nodes.bash'"
    - "-e -p '/etc/slurm/notification_scripts/management.bash'"
    - "-a -p '/etc/slurm/notification_scripts/management.bash'"
    - "-h -p '/etc/slurm/notification_scripts/management.bash'"
    - "-g -p '/etc/slurm/notification_scripts/management.bash'"
  become: true
  become_user: slurm
...
