---
- name: Check if host should use pulp client to access a pulp server for managed repos.
  ansible.builtin.debug:
    msg: "FATAL: expected repo_manager == pulp, but detected {{ repo_manager }}. \
          Check Ansible repo_manager variable in the group_vars for this site."
  when: repo_manager != 'pulp'
  failed_when: repo_manager != 'pulp'

- name: Add Pulp yum repos.
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ pulp_server_url }}"
    gpgcheck: false
  vars:
    pulp_server_url: >-
        {%- if repo_manager == 'pulp' -%}
          https://{{ groups['repo'] | first }}/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/{{ item.name }}/
        {%- else -%}
          none
        {%- endif -%}
  loop: "{{ pulp_repos[os_distribution] | flatten(levels=1) }}"
  loop_control:
    label: "name: {{ item.name }} | desc: {{ item.description }} | url: {{ pulp_server_url }}"
  become: true

- name: Copy pulp web server certificates to pulp clients.
  ansible.builtin.copy:
    src: "{{ stack_name }}/{{ item }}_pulp_root.crt"
    dest: /etc/pki/ca-trust/source/anchors/
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ groups['repo'] }}"
  become: true
  notify: update-ca-trust

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Find all *.repo files in /etc/yum.repos.d/.
  ansible.builtin.find:
    paths: '/etc/yum.repos.d/'
    use_regex: false
    patterns: '*.repo'
  register: yum_repo_configs

- name: Remove *.repo files from /etc/yum.repos.d/ that do not correspond to our Pulp repos.
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ yum_repo_configs.files | map(attribute='path') | list }}"
  vars:
    pulp_repo_names: "{{ pulp_repos[os_distribution] | map(attribute='name') | list }}"
  when: item | basename | regex_replace('.repo$','') not in pulp_repo_names
  become: true

- name: Remove RHN/SpaceWalk if it was installed.
  ansible.builtin.package:
    state: absent
    name:
      - rhn-client-tools
      - rhn-check
      - rhn-setup
      - rhnsd
      - yum-rhn-plugin
  become: true
...
