---
- name: Configure logstoprm chaperone user, ssh settings and cron script/jobs
  ansible.builtin.include_tasks:
    file: logstoprm.yml
  when: inventory_hostname in groups['chaperone'] | default([])
...
