---
openstack_api_timeout: 180
#
# network_names_of_all_hosts_created_in_openstack are the ones specified in the inventory for hosts,
# which also have a `cloud_flavor` specified, indicating these machines are created in OpenStack.
#
network_names_of_all_hosts_created_in_openstack: "{{ hostvars
    | json_query('* | [?cloud_flavor] | [].host_networks[].name')
    | flatten
    | unique }}"
inventory_groups_with_hosts_created_in_openstack: "{{ hostvars
    | json_query('* | [?cloud_flavor] | [].group_names')
    | flatten
    | unique }}"
...
