---
- name: Install EGA Fuse client and its dependencies.
  ansible.builtin.package:
    state: latest
    name:
      - fuse
      - fuse-libs
      - ega-fuse-client
      - java-11-openjdk
  become: true
  notify: restart_ega-fuse-client

- name: Patch fuse lib config file.'
  ansible.builtin.lineinfile:
    path: '/etc/fuse.conf'
    regexp: 'user_allow_other'
    line: 'user_allow_other'
    owner: root
    group: root
    mode: '0644'
  notify: restart_ega-fuse-client
  become: true

- name: Create /etc/ega-fuse-client.d/ directory.
  ansible.builtin.file:
    path: /etc/ega-fuse-client.d/
    state: directory
    mode: '0750'
    owner: root
    group: root
  become: true
  notify: restart_ega-fuse-client

- name: Check mount point status.
  ansible.builtin.shell: '/bin/mountpoint {{ item.value }} 2>&1'
  with_dict: "{{ ega_fuse_client_mounts }}"
  register: mountpoint_status
  changed_when: "mountpoint_status.rc != 0"
  failed_when: false
  become: true

- name: Create mount points.
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '0550'
    owner: root
    group: root
  when: mountpoint_status | json_query(query) | first != 0
  vars:
    query: "results[?item.key=='{{ item.key }}'].rc"
  with_dict: "{{ ega_fuse_client_mounts }}"
  become: true
  notify: restart_ega-fuse-client

- name: Install *.env files for service instances in /etc/ega-fuse-client.d/.
  ansible.builtin.template:
    src: templates/ega-fuse-client.env
    dest: "/etc/ega-fuse-client.d/{{ item.key }}.env"
    mode: '0640'
    owner: root
    group: root
  with_dict: "{{ ega_fuse_client_mounts }}"
  become: true
  notify: restart_ega-fuse-client

- name: Install *.cf files for service instances in /etc/ega-fuse-client.d/.
  ansible.builtin.template:
    src: templates/ega-fuse-client.cf
    dest: "/etc/ega-fuse-client.d/{{ item.key }}.cf"
    mode: '0640'
    owner: root
    group: root
  with_dict: "{{ ega_fuse_client_mounts }}"
  become: true
  notify: restart_ega-fuse-client

- name: Install service unit template file.
  ansible.builtin.template:
    src: 'templates/ega-fuse-client@.service'
    dest: '/usr/lib/systemd/system/ega-fuse-client@.service'
    mode: '0644'
    owner: root
    group: root
  tags:
    - service-files
  become: true
  notify: restart_ega-fuse-client

- name: Make sure ega-fuse-client service instances are enabled and started.
  ansible.builtin.systemd:
    name: "ega-fuse-client@{{ item.key }}.service"
    state: started
    enabled: true
    daemon_reload: true
  with_dict: "{{ ega_fuse_client_mounts }}"
  become: true
...
