---
#
# Local group specs.
# Note:
#  * All local groups are listed here.
#  * In ../[stack_name]/vars.yml we list which groups are created locally on which stack.
#  * Never ever change nor recycle a GID value here unless you are in for a surprise...
#
auth_groups:
  admin:
    gid: 20000
  docker:
    gid: 20001
  users:
    gid: 20002
  depad:
    gid: 20003
  solve-rd:
    gid: 20004
  umcg-atd:
    gid: 20005
  funad:
    gid: 20006
  umcg-gap:
    gid: 20007
  umcg-gd:
    gid: 20008
  umcg-genomescan:
    gid: 20009
  umcg-gsad:
    gid: 20010
  umcg-gst:
    gid: 20011
  umcg-vipt:
    gid: 20012
  umcg-depad:
    gid: 20013
  umcg-funad:
    gid: 20014
  #
  # FUNctional USers group.
  # Used for all functional accounts on chaperone machines:
  #  * All functional accounts must be a member of this group.
  #  * Group is added to /etc/security/access.conf maintained by central IT dept.
  #  * Ensures (local) functional accounts can login and use cron.
  #
  umcg-funus:
    gid: 20015
  umcg-labgnkbh:
    gid: 20016
  umcg-patho:
    gid: 20017
  umcg-lab:
    gid: 20018
  vipt:
    gid: 20019
  umcg-pr:
    gid: 20020
  umcg-logstoprm:
    gid: 20021
  MEDGEN-NFG GCC Analyse Team:
    gid: 4560734
  lsaai:
    gid: 20022
  umcg-ogm:
    gid: 20023
  umcg-pgx:
    gid: 20024
  repo:
    gid: 20025
...
