---
ip_addresses:
  cf-dragen:
    vlan16:
      address: 195.169.22.43
      netmask: /32
    vlan990:
      address: 192.168.1.62
      netmask: /32
    vlan990_bmc:
      address: 10.10.1.102
      netmask: /32
  cf-porch:
    cf_internal_management:
      address: 10.10.1.86
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external:
      address: 195.169.23.116
      netmask: /32
      fqdn: 'NXDOMAIN'
  cf-transfer:
    cf_internal_management:
      address: 10.10.1.42
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external:
      address: 195.169.23.88
      netmask: /32
      fqdn: 'cf-transfer.hpc.rug.nl'
  copperfist:
    vlan983:
      address: 172.23.41.226
      netmask: /32
    vlan16:
      address: 195.169.22.4
      netmask: /32
    vlan990:
      address: 192.168.1.22
      netmask: /32
  cf_internal_management-external-router:
    cf_internal_management:
      address: 10.10.1.1
      netmask: /32
    external:
      address: 195.169.23.125
      netmask: /32
      fqdn: 'NXDOMAIN'
...
