---
- name: "Include group_vars/{{ external_stack }}/ssh_client_settings.yml."
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/group_vars/{{ external_stack }}/ssh_client_settings.yml"
    name: ssh_client_settings_for_external_stack
  delegate_to: localhost
  connection: local
  run_once: true

- name: "Add public key for {{ external_stack }} CA to /etc/ssh/ssh_known_hosts."
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    mode: '0644'
    owner: root
    group: root
    create: true
    insertbefore: BOF
    regexp: '(?i)^#?@cert-authority .* for {{ external_stack }}$'
    line: "{{ ssh_client_settings_for_external_stack['ssh_client_known_hosts'] }} for {{ external_stack }}"
  when:
    - ssh_client_settings_for_external_stack['ssh_client_known_hosts'] is defined
    - ssh_client_settings_for_external_stack['ssh_client_known_hosts'] is not none
    - ssh_client_settings_for_external_stack['ssh_client_known_hosts'] | default('') | length >= 1
  become: true

- name: Create /etc/ssh/ssh_config.d/ dir.
  ansible.builtin.file:
    path: /etc/ssh/ssh_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when:
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is defined
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is not none
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] | default('') | length >= 1
  become: true

- name: "Create /etc/ssh/ssh_config.d/{{ external_stack }}.conf config file."
  ansible.builtin.template:
    src: ssh_client_config.j2
    dest: "/etc/ssh/ssh_config.d/{{ external_stack }}.conf"
    owner: root
    group: root
    mode: '0644'
  when:
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is defined
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is not none
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] | default('') | length >= 1
  become: true
...
