---
- name: Create versioned projects and releases
  ansible.builtin.include_tasks:
    file: versions_and_projects_main.yml
  when:
    - inventory_hostname in groups['sys_admin_interface']

- name: Check if privilege escalation is possible
  ansible.builtin.command: whoami
  register: become_check
  changed_when: false
  failed_when: false
  ignore_errors: true
  when:
    - inventory_hostname in groups['user_interface']
  become: true

- name: Deploy hierarchical structure tools
  ansible.builtin.include_tasks:
    file: hierarchical_auto_ldap_structure.yml
  when:
    - inventory_hostname in groups['user_interface']
    - become_check is defined
    - become_check is succeeded
...
