---
- name: Create a local yum repository.
  ansible.builtin.include_tasks:
    file: yum_local_create.yml
  when: local_yum_repository | bool is true

- name: Remove a local yum repository.
  ansible.builtin.include_tasks:
    file: yum_local_remove.yml
  when: local_yum_repository | bool is false
...
