---
- name: Configure ldap with ldif files
  ansible.builtin.command:
    cmd: >
      /usr/local/openldap/bin/ldapadd -x -H "ldap://localhost"
      -D "{{ ldap_credentials['stack']['admin']['dn'] }}"
      -w "{{ ldap_credentials['stack']['admin']['pw'] }}"
      -f '/tmp/configure_lsaai-{{ item }}'
  with_items:
    - ldap_groups_ou.ldif
    - ldap_users_ou.ldif
  register: lsaai_ldapadd_result
  failed_when: false
  changed_when: lsaai_ldapadd_result.rc == 0
  become: true
  become_user: lsaai
  listen: lsaai_ldapadd

- name: Extend LDAP with LSAAI extra fields
  ansible.builtin.command:
    cmd: >
      /usr/local/openldap/bin/ldapadd
      -Y EXTERNAL
      -H 'ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi'
      -f /usr/local/openldap/etc/openldap/custom/lsaai.ldif
  register: lsaai_schema_extend_result
  failed_when: lsaai_ldapadd_result.rc != 0
  changed_when:
    - lsaai_schema_extend_result.rc == 0
    - "'adding new entry' in lsaai_schema_extend_result.stdout"
    - "'cn=lsaai,cn=schema,cn=config' in lsaai_schema_extend_result.stdout"
  become: true
  listen: lsaai_schema_extend
...
