# Install  MariaDB.
---
- name: 'Install mariadb-server.'
  ansible.builtin.package:
    name:
      - 'mariadb-server'
    state: 'latest'
    update_cache: true
  notify:
    - 'restart_mariadb'
  become: true

- name: 'Create/check dirs used by MariaDB/MySQL.'
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: 'directory'
    mode: "{{ item.mode }}"
    owner: "{{ item.og }}"
    group: "{{ item.og }}"
  with_items:
    - path: '/var/lib/mysql'
      mode: '0755'
      og: 'mysql'
    - path: '/etc/my.cnf.d/'
      mode: '0755'
      og: 'root'
  become: true

- name: 'Deploy MariaDB/MySQL galara.cnf on node if we have at least three nodes.'
  ansible.builtin.template:
    src: 'files/galera.cnf'
    dest: '/etc/my.cnf.d/galera.cnf'
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify:
    - restart_mariadb
  when: "'databases' in group_names and groups['databases'] | length >= 3"
  become: true

- name: 'Deploy MariaDB/MySQL config files.'
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/my.cnf.d/{{ item }}"
    mode: '0644'
    owner: 'root'
    group: 'root'
  with_items:
    - 'innodb.cnf'
  notify:
    - 'restart_mariadb'
  become: true

- name: 'Make sure the MariaDB/MySQL service is enabled and started.'
  ansible.builtin.systemd:
    name: 'mariadb.service'
    state: 'started'
    enabled: 'yes'
    daemon_reload: 'yes'
  become: true

- name: Install dependencies for EL 7.
  ansible.builtin.import_tasks: el7-deps.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: Install dependencies for EL >= 8.
  ansible.builtin.import_tasks: el8-deps.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "8"

- name: Gather list of installed packages.
  ansible.builtin.package_facts:
    manager: auto

# Not required on MariaDB >= 10.4, which uses sockets by default 
# and has the password based login for root disabled by default
# Standard installation has the root account configure with an 'invalid' password.
#
- name: Set root password for MariaDB < 10.4.
  ansible.builtin.import_tasks: set_root_password.yml
  when:
    - ansible_facts.packages['mariadb'][0]['version'] is version_compare('10.4', operator='<')

#
# Must flush handlers explicitly, because this role is included as dependency for Slurm.
# Without explicit flush the handlers will run after the slurm rol tasks,
# which is too late resulting in Slurm unable to work with the Slurm Accounting DB.
#
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: 'Give the MariaDB/MySQL master node some time to initialize the database cluster.'
  ansible.builtin.command: bash -c "sleep 60"
  when: "'databases' in group_names and groups['databases'] \
         | length >= 3"

- name: 'Give the MariaDB/MySQL cluster some time to initialize replication.'
  ansible.builtin.command: bash -c "sleep 60 && systemctl daemon-reload"
  when: "'databases' in group_names and groups['databases'] | length >= 3"
  become: true
