---
#
# This command will fail when the root password was set previously
#
- name: 'Check if MariaDB/MySQL root password is set.'
  ansible.builtin.command:
    cmd: mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
#
# Secure MariaDB root account by setting a password on MariaBB < 10.4.x
# Note: no longer required on MariaDB >= 10.4,
# which uses sockets by default and has the password based login for root disabled,
# by setting an 'invalid' password.
#
- name: 'Set MariaDB/MySQL root user password.'
  community.mysql.mysql_user:
    name: 'root'
    host: 'localhost'
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    check_implicit_admin: true
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    login_user: 'root'
    login_password: ''
    state: 'present'
  when: root_pwd_check.rc == 0
...
