---
- name: Enable fail2ban.
  ansible.builtin.package:
    name: fail2ban
    state: present
  become: true

- name: Copy fail2ban custom configuration file into place.
  ansible.builtin.template:
    src: "{{ basic_security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure fail2ban is running and enabled on boot.
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true
...
