---
slurm_cluster_name: 'hyperchicken'
stack_domain: ''
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'hc'
slurm_version: '22.05.2-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
figlet_font: 'lockergnome'
motd: "To solve or not to solve, that's the question."
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs_on_merlin
        network: vlan16
use_ldap: true
use_sssd: true
ldap_domains:
  stack:
    uri: "ldaps://{{ stack_prefix }}-dai"
    base: "dc={{ stack_name }},dc=local"
    schema: rfc2307bis
    min_id: 1000
    max_id: 21999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: memberOf
    group_member: member
    create_ldap: true
    ldap_db_index: 3  # Indices up to 2 are already used by default for the "config", "monitor" and "example" databases.
cloud_image: CentOS7-Cloud
cloud_user: centos
network_public_external_id: public
network_private_management_id: "{{ stack_prefix }}_internal_management"
network_private_management_cidr: '10.10.1.0/24'
network_private_management_gw: '10.10.1.1'
network_private_storage_id: "subnet-nfs-data-2541"
network_private_storage_cidr: '10.35.141.0/24'
network_private_storage_allow_ingress:  # Extra network ranges for which to allow any inbound network traffic.
  - 10.35.141.251/32  # NFS server
availability_zone: nova
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
envsync_user: 'envsync'
envsync_group: 'depad'
functional_admin_group: 'funad'
hpc_env_prefix: '/apps'

archive_groups:
  - 'umcg-atd'
  - 'solve-rd'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'users'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mbenjamins'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
#
# Shared storage related variables
#
pfs_mounts:
  - pfs: ecst01
    source: '10.35.141.251:/solve-rd-98599485'
    type: nfs4
    rw_options: 'defaults,_netdev,noatime,nodiratime,rw'
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
lfs_mounts:
  - lfs: home
    pfs: ecst01
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp09
    pfs: ecst01
    groups:
      - name: umcg-atd
      - name: solve-rd
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_vm'] }}"
  - lfs: prm09
    pfs: ecst01
    groups:
      - name: umcg-atd
      - name: solve-rd
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: env09
    pfs: ecst01
    ro_machines: "{{ groups['compute_vm'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
ega_fuse_client_mounts:
  solve_rd: '/groups/solve-rd/prm09/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
