---
#
# Lustre 'project' quota is preferred, but older Lustre versions may not support it;
# Fall-back is 'group' quota, which will work with older versions too.
# Setting is global for all Lustre file systems mounted on a cluster.
# Hence you cannot have one older Lustre file system with 'group'
# and a newer one with 'project' quota mounted on the same cluster.
#
lustre_quota_type: 'project'
...
