---
shared_storage_default_dat_lfs_mode: '2770'
shared_storage_default_dat_lfs_cifs_dir_mode: '02770'
shared_storage_default_dat_lfs_cifs_file_mode: '0660'
shared_storage_default_prm_lfs_mode: '2750'
shared_storage_default_prm_lfs_cifs_dir_mode: '02750'
shared_storage_default_prm_lfs_cifs_file_mode: '0640'
shared_storage_default_rsc_lfs_mode: '2750'
shared_storage_default_rsc_lfs_cifs_dir_mode: '02750'
shared_storage_default_rsc_lfs_cifs_file_mode: '0640'
shared_storage_default_tmp_lfs_mode: '2750'
shared_storage_default_tmp_lfs_cifs_dir_mode: '02750'
shared_storage_default_tmp_lfs_cifs_file_mode: '0640'
...
