---
# If possible (higly recommended), define this variables in the group variables,
# since both playbooks 'rsyslog_server' and 'rsyslog_client' are both using it
rsyslog_remote_path_key_dir: "/etc/pki/tls/private/"
rsyslog_remote_path_cert_dir: "/etc/pki/tls/certs/"
rsyslog_ca_key_file: "logs_{{ logs_class }}.key"
rsyslog_ca_cert_file: "logs_{{ logs_class }}.pem"
rsyslog_repository_dir: "{{ playbook_dir }}/files/logs_library/"

# Iptables additional configurations
iptables_extras_dir: '/etc/iptables_extras.d/'
...
