---
stack_prefix: 'logs'
stack_domain: ''
stack_name: "{{ stack_prefix }}_library"  # stack_name must match the name of the folder that contains this vars.yml file.
os_distribution: 'rocky9'
cloud_image: RockyLinux-9.3_xfs
cloud_user: centos
availability_zone: nova
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    gateway: '10.10.1.1'
    router_network: vlan16
    type: management
    external: false
    mtu_size: '1450'
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'

# To limit access to sensitive logs, access is limited to: NEED-TO-HAVE personnel
local_admin_users:
  - 'gerben'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
regular_groups:
  - 'umcg-logstoprm'
regular_users:
  - user: "logstoprm"
    groups: "umcg-logstoprm"
# Logs CA key name: 'development' (default), 'research' or 'diagnostics'
logs_class: 'development'
# logs collecting variables for rsyncd modules and logs_servers cron scripts
logstoprm_rsyncd_module:
  username: 'logstoprm'          # must be defined in users.yml and ^ in regular_users
  group: 'umcg-logstoprm'        # must be defined ^ in regular_groups
  rsyncd_dir: '/mnt/logstoprm'
  cron_disabled: false

use_ldap: false
create_ldap: false
use_sssd: false

#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: gearshift_cluster
    hosts:
    - hostname: airlock
      network: vlan16
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network: public
  - group: fender_cluster
    hosts:
      - hostname: corridor
        network: public
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
...
