---
- name: 'Check if required groups are present.'
  ansible.builtin.group:
    name: "{{ group['name'] }}"
    gid: "{{ auth_groups[group['name']]['gid'] }}"
    state: present
  loop: "{{ regular_groups }}"
  loop_control:
    loop_var: group
  become: true

- name: "Check if required private groups for user's home dir are present."
  ansible.builtin.group:
    name: "{{ user['name'] }}"                 # Use same name as user's account name for user's private group.
    gid: "{{ auth_users[user['name']]['uid'] }}"  # Use same GID as user's UID for user's private group.
    state: present
  loop: "{{ regular_users }}"
  loop_control:
    loop_var: user
  become: true

- name: 'Create local regular users and append them to relevant groups.'
  ansible.builtin.user:
    name: "{{ user['name'] }}"
    uid: "{{ auth_users[user['name']]['uid'] }}"
    comment: "{{ auth_users[user['name']]['comment'] }}"
    group: "{{ user['name'] }}"
    groups: "{{ user['groups'] }}"
    shell: "{{ auth_users[user['name']]['shell'] if auth_users[user['name']]['shell'] is defined | default(omit) }}"
    home: "/home/{{ user['name'] }}"
    append: false
  loop: "{{ regular_users }}"
  loop_control:
    loop_var: user
  become: true

- name: 'Deploy authorized keys for local regular users.'
  ansible.posix.authorized_key:
    user: "{{ user['name'] }}"
    key: "{{ auth_users[user['name']]['pub_keys'] }}"
    state: present
    exclusive: true
  loop: "{{ regular_users }}"
  loop_control:
    loop_var: user
  become: true
...
