---
- name: Create local groups for local linux user, which will be mapped to samba user.
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
    local: true
  with_items: "{{ smb_server_users | map(attribute='groups') | list | flatten | unique }}"
  become: true

- name: Create local private group for local linux user, which will be mapped to samba user.
  ansible.builtin.group:
    name: "{{ item.name }}"  # Use same name as user's account name for user's private group.
    gid: "{{ item.uid }}"    # Use same GID as user's UID for user's private group.
    state: present
  with_items: "{{ smb_server_users }}"
  become: true

- name: Create local linux users for smb users and append them to relevant groups.
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    comment: "Local linux account only used for corresponding smb account"
    group: "{{ item.name }}"
    groups: "{{ item.groups | map(attribute='name') | list }}"
    home: /dev/null
    shell: /bin/false
    append: false
  with_items: "{{ smb_server_users }}"
  become: true
...
