---
- name: Install tools to work with block devices and mount points.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name:
      - util-linux  # Will also install util-linux-core
  become: true

- name: Check the file system type of the device.
  ansible.builtin.command: "lsblk -n -o FSTYPE {{ volume_device }}"
  register: device_status
  changed_when: false

- name: Check the mount point.
  ansible.builtin.command: "mountpoint {{ volume_mount_point }}"
  register: mount_point_status
  failed_when: mount_point_status.rc not in [0, 1, 32]
  changed_when: false

- name: Create a filesystem on the device.
  community.general.filesystem:
    fstype: "{{ volume_type }}"
    dev: "{{ volume_device }}"
    force: false
    resizefs: true
  when:
    #
    # Nothing is mounted at the mount point
    # and when the device is unformatted.
    #
    - mount_point_status['rc'] != 0
    - device_status['stdout'] != volume_type
  become: true
...
