---
- name: Compile the list of logs server names
  ansible.builtin.set_fact:
    logs_class_servers: "{{ logs_class_servers | default([]) + [item.name] }}"
  loop: "{{ logs_server_public_networks[logs_class] }}"
  when: logs_class is defined and logs_class|length>0
  register: rsys_ext_ips
  delegate_to: localhost
  connection: local
  run_once: true
  tags:
    - test

- name: Open logs server firewall for each client
  ansible.builtin.include_tasks:
    file: firewall.yml
  when: ( logs_class is defined and ( logs_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))

- name: Deploy rsyslog client
  ansible.builtin.include_tasks:
    file: deploy.yml
  when: ( logs_class is defined and ( logs_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))

- name: Test rsyslog client
  ansible.builtin.include_tasks:
    file: test.yml
  when: ( logs_class is defined and ( logs_class|length>0 ) ) or
        ( rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 ))
  tags:
    - test
...
