---
- name: Install packages for build environment to support Dynamic Kernel Module Support (DKMS).
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - asciidoc
      - audit-libs-devel
      - automake
      - bc
      - binutils-devel
      - bison
      - device-mapper-devel
      - elfutils-devel
      - elfutils-libelf-devel
      - expect
      - flex
      - gcc
      - gcc-c++
      - git
      - glib2
      - glib2-devel
      - hmaccalc
      - keyutils-libs-devel
      - krb5-devel
      - ksh
      - libattr-devel
      - libblkid-devel
      - libselinux-devel
      - libtool
      - libuuid-devel
      - libyaml-devel
      - lsscsi
      - make
      - ncurses-devel
      - net-snmp-devel
      - net-tools
      - newt-devel
      - numactl-devel
      - parted
      - patchutils
      - pciutils-devel
      - perl-ExtUtils-Embed
      - pesign
      - python-devel
      - redhat-rpm-config
      - rpm-build
      - systemd-devel
      - tcl
      - tcl-devel
      - tk
      - tk-devel
      - wget
      - xmlto
      - yum-utils
      - zlib-devel
  become: true

- name: Install kernel tools/extras required for compiling kernel modules.
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - dkms
      - kernel
      - kernel-devel
      - kernel-headers
      - kernel-tools
      - kernel-tools-libs
      - kernel-tools-libs-devel
  become: true
  notify: reboot

- name: Install kernel tools/extras required for compiling kernel modules - for RedHat == 7.
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - kernel-abi-whitelists
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
  become: true
  notify: reboot

- name: Install kernel tools/extras required for compiling kernel modules - for RedHat >= 8.
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - kernel-abi-stablelists
      - kernel-rpm-macros
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "8"
  become: true
  notify: reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

#
# For EL >= 9.3 we need a patched Lustre >= 2.15.4, because Lustre 2.15.3 will no longer compile with DKMS.
#
# At the time this comment was written 2.15.4 was not yet released and we need to
# * Fetch the source code for 2.15.4-RC2
# * Patch that to remove the dependency on python2, which is not available in EL 9.x
#   Simply change "#!/usr/bin/env python2" to "#!/usr/bin/env python3" in contrib/scripts/branch_comm
#   That script is only used to manage the source code in git and not used by Lustre itself: we do not need it.
# * Compile code and create RPMs with instructions from
#   lustre-client-dkms: https://wiki.lustre.org/Compiling_Lustre#Lustre_Client_(DKMS_Packages_only)
#   lustre-client:      https://wiki.lustre.org/Compiling_Lustre#Lustre_Client_(All_other_Builds)
# * Add those custom RPMs to the cpel repo on our repo servers.
# The RPMs
#  * lustre-client-dkms-2.15.4_RC2-1.el9.noarch.rpm
#  * lustre-client-2.15.4_RC2-1.el9.x86_64.rpm
# can then be installed with the normal procedure and the ansible task below.
#
# For EL >= 9.4 we need Lustre >= 2.15.5, because Lustre 2.15.4 will no longer compile with DKMS.
#
# At the time this comment was written 2.15.5 was not yet released and we need to
# * Fetch the source code for 2.15.5-RC1
# * Use the same procedure as above to compile lustre-*2.15.5_RC1-1.el9.*.rpm RPMs.
#
- name: Install the Lustre client
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - lustre-client-dkms
      - lustre-client
  become: true

- name: Load the Lustre kernel modules.
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - lnet
    - lustre
  become: true

- name: Remove old style /etc/modprobe.d/lustre.conf.
  ansible.builtin.file:
    path: /etc/modprobe.d/lustre.conf
    state: absent
  become: true

- name: 'Create lustre lnet config: part 1.'
  ansible.builtin.command:
    cmd: |
         lnetctl lnet configure
  changed_when: true
  become: true

- name: 'Create lustre lnet config: part 2.'
  ansible.builtin.command:
    cmd: |
         lnetctl net del --net tcp
  register: lnetctl_del_status
  changed_when:
    - lnetctl_del_status.rc == 0
  failed_when:
    - lnetctl_del_status.rc > 0
    - '"errno: -2" not in lnetctl_del_status.stderr'
  become: true

- name: 'Create lustre lnet config: part 3.'
  ansible.builtin.command:
    cmd: |
         lnetctl net add --net "{{ item.name }}" --if "{{ item.interface }}"
  register: lnetctl_add_status
  changed_when:
    - lnetctl_add_status.rc == 0
  failed_when:
    - lnetctl_add_status.rc > 0
    - '"errno: -17" not in lnetctl_add_status.stderr'
  with_items: "{{ lustre_client_networks }}"
  become: true

- name: Save lustre lnet config to /etc/lnet.conf
  ansible.builtin.shell:
    cmd: |
         checksum_old=$(md5sum /etc/lnet.conf)
         lnetctl export -b /etc/lnet.conf
         checksum_new=$(md5sum /etc/lnet.conf)
         if [[ "${checksum_old}" != "${checksum_new}" ]]; then
             echo 'lnet.conf has changed.'
         fi
  register: lnetconf_status
  changed_when:
    - '"lnet.conf has changed." in lnetconf_status.stdout'
  notify:
    - restart_lnet
  become: true

- name: Patch lnet.service file for systemd to ignore failure if a Lustre network ID was already loaded.
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/lnet.service
    backup: true
    insertafter: '\[Service\]'
    regexp: '^#?SuccessExitStatus='
    line: 'SuccessExitStatus=239'  # lustre NID already loaded.
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_lnet
  become: true

- name: Patch lnet.service file for systemd to start lnet.service before remote-fs.target.
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/lnet.service
    backup: true
    insertafter: '\[Install\]'
    regexp: '^#?WantedBy='
    line: 'WantedBy=multi-user.target remote-fs-pre.target'
    owner: root
    group: root
    mode: '0644'
  notify:
    - reenable_lnet
    - restart_lnet
  become: true

- name: Start lnet.service.
  ansible.builtin.systemd:
    name: lnet.service
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Flush handlers for Lustre client.
  ansible.builtin.meta: flush_handlers
...
