---
ip_addresses:
  jenkins:
    jenkins_internal_management:
      address: 10.10.1.181
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external:
      address: 195.169.23.117
      netmask: /32
      fqdn: 'jenkins.gcc.rug.nl'
  jenkins_internal_management-external-router:
    jenkins_internal_management:
      address: 10.10.1.1
      netmask: /32
    external:
      address: 195.169.23.152
      netmask: /32
      fqdn: 'NXDOMAIN'
...
