---
stack_prefix: 'jenkins'
stack_name: "{{ stack_prefix }}_server"  # stack_name must match the name of the folder that contains this vars.yml file.
cloud_image: RockyLinux-9.3_xfs
cloud_user: cloud-user
availability_zone: nova
os_distribution: 'rocky9'
repo_manager: 'none'
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    gateway: '10.10.1.1'
    router_network: external
    type: management
    external: false
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'

use_ldap: false
create_ldap: false
use_sssd: false
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: vaxtron_cluster
    hosts:
    - hostname: foyer
      network: external
  - group: gearshift_cluster
    hosts:
    - hostname: airlock
      network: vlan16
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network: public
  - group: fender_cluster
    hosts:
      - hostname: corridor
        network: public
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
jenkins_plugins:
  - warnings-ng
  - name: git
    version: 5.2.2
  - name: branch-api
    version: 2.1169.va_f810c56e895
  - name: cloudbees-folder
    version: 6.901.vb_4c7a_da_75da_3
  - name: github-branch-source
    version: 1789.v5b_0c0cea_18c3
  - name: analysis-model-api
    version: 12.3.3
  - name: ghprb
    version: 1.42.2
  - name: github-api
    version: 1.318-461.v7a_c09c9fa_d63
  - name: git-client
    version: 4.7.0
  - name: github
    version: 1.38.0
  - name: matrix-auth
    version: 3.2.2
  - name: workflow-api
    version: 1291.v51fd2a_625da_7
  - name: workflow-job
    version: 1400.v7fd111b_ec82f
  - name: workflow-multibranch
    version: 773.vc4fe1378f1d5
  - name: workflow-basic-steps
    version: 1058.vcb_fc1e3a_21a_9
  - name: workflow-durable-task-step
    version: 1353.v1891a_b_01da_18
  - name: workflow-scm-step
    version: 427.v4ca_6512e7df1
  - name: pipeline-stage-step
    version: 312.v8cd10304c27a_

jenkins_plugins_install_dependencies: true
jenkins_prefer_lts: true
jenkins_shellcheck_version: 0.8.0
jenkins_url: 'http://localhost:8080/'
jenkins_cli_dest: '/opt/jenkins-cli.jar'
jenkins_xml_dest: '/var/lib/jenkins/xml_files/'
jenkins_projects: 
  - 'GAP'
  - 'NGS_DNA'
  - 'NGS_RNA'
...
