---
- name: "Configure options for {{ yum_repo['id'] }} in {{ yum_repos_repo_config_dir }}/{{ yum_repo['file'] }}."
  community.general.ini_file:
    path: "{{ yum_repos_repo_config_dir }}/{{ yum_repo['file'] }}"
    section: "{{ yum_repo['id'] }}"
    no_extra_spaces: true
    create: true
    option: "{{ item }}"
    value: "{{ yum_repo[item] }}"
    owner: root
    group: root
    mode: '0644'
  when: yum_repo[item] is defined
  loop_control:
    label: "{{ item }}={{ yum_repo[item] | default('undefined') }}"
  loop:
    - name
    - baseurl
    - mirrorlist
    - metalink
    - enabled
    - countme
    - gpgcheck
    - gpgkey
  become: true

- name: "Configure gpgkey option for {{ yum_repo['id'] }} in {{ yum_repos_repo_config_dir }}/{{ yum_repo['file'] }} if we downloaded the GPG key."
  community.general.ini_file:
    path: "{{ yum_repos_repo_config_dir }}/{{ yum_repo['file'] }}"
    section: "{{ yum_repo['id'] }}"
    no_extra_spaces: true
    create: true
    option: gpgkey
    value: "file://{{ yum_repos_gpgkeys_dir }}/{{ yum_repo['gpgkeysource'] | basename }}"
    owner: root
    group: root
    mode: '0644'
  when: yum_repo['gpgkeysource'] is defined
  become: true
...
