---
# Cloud image default user console password
cloud_console_pass: ''
# Pulp password and secret
pulp_api_password: ''
pulp_secret: ''
# LDAP credentials
openldap_root_pw: ''
openldap_root_hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ openldap_root_pw }}'"
ldap_credentials:
  stack:
    readonly:
      dn: 'cn=readonly,dc={{ use stack_name here }},dc=local'
      pw: ''
      hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ the pw for this user }}'"
    admin:
      dn: 'cn={{ use stack_prefix here }}-admin,dc={{ use stack_name here }},dc=local'
      pw: ''
      hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ the pw for this user }}'"
# Database user and password to be used by slurmdbd
slurm_storage_user: slurm
slurm_storage_pass: ''
#slurm_notification_slack_webhook: 'https://hooks.slack.com/.... For NHC messages forwarded to Slack'
# Password of the (external) prometheus alertmanager to contact.
#alertmanager_pass: ''
# Root password for slurm MySQL/MariaDB database.
MYSQL_ROOT_PASSWORD: ''
# The password of the CA's ssh host signing private key.
ssh_host_signer_ca_private_key_pass: ''
# The htaccess for the reverse proxy that proxies Prometheus.
#prom_proxy_htpasswd: ''
...