---
#
# Important: maintain correct handler order.
# Handlers are executed in the order in which they are defined
# and not in the order in which they are listed in a "notify: handler_name" statement!
#
- name: Restart cgconfig service.
  ansible.builtin.systemd:
    name: cgconfig.service
    state: restarted
    daemon_reload: true
  become: true
  listen: restart_cgconfig

- name: Restart cgred service.
  ansible.builtin.systemd:
    name: cgred.service
    state: restarted
    daemon_reload: true
  become: true
  listen: restart_cgred
...
