#
# Three different users are required for a complete Pulp instalation.
#
# 1. repo_management_user:
#    This is a Linux user/account. Users in the Linux admin group can sudo to this user to manage Pulp manually.
#    E.g. create/update/delete artifacts, repositories, remotes, publications and distributions.
#
# 2. pulp_api_user:
#    This is the account used by the repo_management_user to login to the Pulp API to work with Pulp.
#    The pulp_api_password is for this account.
#
# 3. pulp_user:
#    This is a Linux user/account, which is used to run the Pulp daemons/services.
#    Not specified here, but configured in the pulp.pulp_installer.pulp_all_services role we depend on.
#
repo_management_user: repoadmin
pulp_api_user: admin
pulp_api_host: localhost
pulp_api_port: 24817
pulp_api_baseurl: "http://{{ pulp_api_host }}:{{ pulp_api_port }}"
pulp_default_admin_password: "{{ pulp_api_password }}"
# Prevent installation of broken EPEL config via RPM from basos repo.
pulp_repos_epel_enable: false  # EPEL already installed via yum_repos role.
pulpcore_version: "3.16.9"
pulp_install_plugins:
  # galaxy-ng: {}
  # pulp-2to3-migration: {}
  # pulp-ansible: {}
  # pulp-certguard: {}
  # pulp-container: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-file: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-npm: {}
  # pulp-python: {}
  pulp-rpm:
    version: "3.16.2"
pulp_settings:
  secret_key: "{{ pulp_secret }}"
  content_origin: "{{ pulp_webserver_disable_https | default(false) | ternary('http', 'https') }}://{{ ansible_fqdn }}"
pulp_root_cert_path_on_repo_server: "/etc/pulp/certs/root.crt"
pulp_root_cert_path_on_control_host: "{{ playbook_dir }}/files/{{ stack_name }}/{{ inventory_hostname }}_pulp_root.crt"
#
# List of Pulp server Python dependencies.
# Generated with
#           [pulp@{{ stack_prefix }}-repo:/usr/local/lib/pulp]$ source bin activate
#    (pulp) [pulp@{{ stack_prefix }}-repo:/usr/local/lib/pulp]$ pip freeze
# after first successful installation.
#
prereq_pip_packages:
  - aiodns==3.0.0
  - aiofiles==0.7.0
  - aiohttp==3.7.4.post0
  - aiohttp-xmlrpc==1.4.0
  - aioredis==2.0.0
  - asgiref==3.4.1
  - async-timeout==3.0.1
  - asyncio-throttle==1.0.2
  - attrs==21.2.0
  - backoff==1.11.1
  - cffi==1.15.0
  - chardet==4.0.0
  - click==8.0.3
  - createrepo-c==0.17.6
  - cryptography==35.0.0
  - defusedxml==0.7.1
  - Deprecated==1.2.13
  - diff-match-patch==20200713
  - distro==1.6.0
  - Django==3.2.10
  - django-currentuser==0.5.3
  - django-filter==21.1
  - django-guardian==2.4.0
  - django-guid==3.2.1
  - django-import-export==2.6.1
  - django-lifecycle==0.9.3
  - django-readonly-field==1.0.5
  - djangorestframework==3.12.4
  - djangorestframework-queryfields==1.0.0
  - drf-access-policy==1.1.0
  - drf-nested-routers==0.93.3
  - drf-spectacular==0.20.1
  - dynaconf==3.1.7
  - et-xmlfile==1.1.0
  - gunicorn==20.1.0
  - idna==3.3
  - importlib-metadata==4.10.0
  - importlib-resources==5.4.0
  - inflection==0.5.1
  - Jinja2==3.0.3
  - jsonschema==4.3.2
  - libcomps==0.1.15.post1
  - lxml==4.7.1
  - MarkupPy==1.14
  - MarkupSafe==2.0.1
  - multidict==5.2.0
  - nose==1.3.7
  - odfpy==1.4.1
  - openpyxl==3.0.9
  - packaging==21.3
  - pep517==0.12.0
  - pip-tools==6.4.0
  - productmd==1.33
  - psycopg2==2.9.2
  - pulp-file==1.10.1
  - pulp-rpm==3.16.1
  - pulpcore==3.16.1
  - pycairo==1.20.1
  - pycares==4.1.2
  - pycparser==2.21
  - Pygments==2.10.0
  - PyGObject==3.42.0
  - pygtrie==2.4.2
  - pyparsing==3.0.6
  - pyrsistent==0.18.0
  - python-gnupg==0.4.8
  - pytz==2021.3
  - PyYAML==5.4.1
  - redis==4.0.2
  - scikit-build==0.12.0
  - six==1.16.0
  - solv==0.7.20
  - sqlparse==0.4.2
  - tablib==3.1.0
  - tomli==2.0.0
  - typing_extensions==4.0.1
  - uritemplate==4.1.1
  - urlman==2.0.1
  - whitenoise==5.3.0
  - wrapt==1.13.3
  - xlrd==2.0.1
  - xlwt==1.3.0
  - yarl==1.7.2
  - zipp==3.6.0
os_distribution: 'centos7'
