---
- name: "Create {{ network_name }} network."
  openstack.cloud.network:
    state: present
    name: "{{ network_name }}"
    external: false
    mtu_size: "{{ network_mtu_size | default(omit) }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"

- name: "Assign subnet to {{ network_name }} network."
  openstack.cloud.subnet:
    # 'name' must be the same as 'network_name' or else creating routers for this subnet will fail due to known bug.
    name: "{{ network_name }}"
    network_name: "{{ network_name }}"
    state: present
    cidr: "{{ network_cidr }}"
    no_gateway_ip: true
    enable_dhcp: true
    dns_nameservers: "{{ nameservers }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"
...
