---
slurm_cluster_name: 'marvin'
stack_domain: ''
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'mv'
slurm_version: '22.05.2-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
logs_class: 'development'
repo_manager: 'none'
os_distribution: 'centos7'
figlet_font: 'speed'
motd: |
      ===============================================================
       Welcome to {{ slurm_cluster_name | capitalize }}
      ===============================================================
       WARNING: Proof of Concept cluster without any backups.
       When this cluster has to be redeployed from scratch,
       all data in home dirs and all group dirs will be lost!
      ===============================================================
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs-on-bateleur
        network: external
use_ldap: true
use_sssd: true
ldap_domains:
  stack:
    uri: "ldaps://{{ groups['ldap_server'] | first }}"
    base: "dc={{ stack_name }},dc=local"
    schema: rfc2307bis
    min_id: 1000
    max_id: 21999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: memberOf
    group_member: member
    create_ldap: true
    ldap_db_index: 3  # Indices up to 2 are already used by default for the "config", "monitor" and "example" databases.
cloud_image: CentOS-7-x86_64-GenericCloud-2211
cloud_user: centos
availability_zone: nova
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    gateway: '10.10.1.1'
    router_network: 'Internet-GDR'
    type: management
    external: false
  - name: Weka-vlan4
    cidr: '10.0.4.0/24'
    allow_ingress:
      - '10.0.4.0/24'
    type: storage
    external: false
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'gerben'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
envsync_user: 'envsync'
envsync_group: 'depad'
functional_admin_group: 'funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'users'
  - 'umcg-atd'
  - 'umcg-gsad'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
  - user: 'umcg-gsad-dm'
    groups: ['umcg-gsad']
  - user: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'kdelange'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'mbenjamins'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
  - user: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'umcg-gsad']
sudoers:
  - who: ['%umcg-atd']
    become: 'umcg-atd-dm'
  - who: ['%umcg-gsad']
    become: 'umcg-gsad-dm'
#
# Shared storage related variables
#
pfs_mounts:
  - pfs: bnst01
    source: '10.0.4.120:/Bytesnet'
    type: wekafs
    rw_options: 'net=udp,num_cores=2'
    ro_options: 'net=udp,num_cores=2,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
lfs_mounts:
  - lfs: home
    pfs: bnst01
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp11
    pfs: bnst01
    groups:
      - name: umcg-atd
      - name: umcg-gsad
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_node'] }}"
  - lfs: env11
    pfs: bnst01
    ro_machines: "{{ groups['compute_node'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
