---
- name: Check if system needs to be restarted
  ansible.builtin.command: '/bin/needs-restarting -r'
  register: needs_restarting
  failed_when: 'needs_restarting.rc > 1'
  changed_when: 'needs_restarting.rc == 1'
  become: true
  notify: reboot_server

- name: Reboot system if needed
  ansible.builtin.meta: flush_handlers

- name: Gather facts to get the latest kernel version
  ansible.builtin.setup:
  become: true

- name: Install yum requirements for gpu driver installation
  ansible.builtin.package:
    state: 'installed'
    update_cache: true
    name:
      - 'kernel-devel-{{ ansible_kernel }}'
      - tar
      - bzip2
      - make
      - automake
      - gcc
      - gcc-c++
      - pciutils
      - elfutils-libelf-devel
      - libglvnd-devel
      - bind-utils
      - wget
  become: true

- name: Download a driver installation file from NVidia
  ansible.builtin.get_url:
    url: '{{ gpu_url_dir }}/{{ gpu_runfile }}'
    dest: '/root/{{ gpu_runfile }}'
    mode: '0700'
  become: true

- name: Install driver from .run file
  ansible.builtin.command: '/root/{{ gpu_runfile }} --silent --driver'
  register: install_result
  failed_when: install_result.rc != 0
  changed_when: true
  become: true

- name: Remove installation file
  ansible.builtin.file:
    path: '/root/{{ gpu_runfile }}'
    state: absent
  become: true

...
